services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    image: ares-coordinator:latest
    container_name: ares_coordinator
    ports:
      - "9000:9000"
    environment:
      - COMPUTE_NODES=["http://compute_1:8000","http://compute_2:8000"]
    env_file:
      - .env
    networks:
      - ares_cluster

  compute_1:
    build:
      context: .
      dockerfile: Dockerfile
    image: ares-compute:latest
    container_name: ares_compute_01
    volumes:
      - ./data/node_1:/app/data
    env_file:
      - .env
    networks:
      - ares_cluster

  compute_2:
    image: ares-compute:latest
    container_name: ares_compute_02
    volumes:
      - ./data/node_2:/app/data
    env_file:
      - .env
    networks:
      - ares_cluster
    depends_on:
      - compute_1

networks:
  ares_cluster:
    driver: bridge