apiVersion: v1
kind: Service
metadata:
  name: compute-headless
  namespace: ares
spec:
  clusterIP: None
  selector:
    app: ares-compute
  ports:
    - name: http
      port: 8000
      targetPort: 8000